# Generated by Django 3.1.5 on 2021-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lf_custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
